version: '3'
services:
  mysql-demo:
    container_name: mysql-demo-sql
    image: mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "1111:3306"
    environment:
      MYSQL_DATABASE: "demo"
      MYSQL_USER: "demo"
      MYSQL_PASSWORD: "demo"
      MYSQL_ROOT_PASSWORD: "demo"
